#!/bin/sh
# virtualrb DIR [RUBY] -- setup virtualized Ruby installation

fail() {
  echo "$@" 1>&2
  exit 1
}

DIR=$1
[ -n "$DIR" ] || fail "usage: virtualrb DIR [RUBY]"

RUBY=${2:-$(which ruby)} || fail "error: ruby $RUBY not found"
mkdir "$DIR" 2>/dev/null || fail "error: target directory $DIR exists"
VER=$($RUBY -v) || fail "error: can't find out Ruby version"

cd "$DIR"
DIR=$PWD

mkdir bin gem lib
ln -s bin gem/bin

cat >bin/ruby <<EOF
#!/bin/sh
export GEM_HOME=$DIR/gem
export GEM_PATH=$DIR/gem
export GEMRC=$DIR/gemrc
export PATH=\$GEM_PATH:\$PATH
export RUBYLIB=$DIR/lib:$RUBYLIB
export RUBY=$DIR/bin/ruby
exec $RUBY "\$@"
EOF

cat >gemrc <<EOF
gem: --no-user-install --no-ri --no-rdoc
EOF

cat >bin/gem <<EOF
#!/bin/sh
$DIR/bin/ruby -S gem "\$@"
EOF

cat >bin/irb <<EOF
#!/bin/sh
$DIR/bin/ruby -S irb "\$@"
EOF

cat >VIRTUALRB <<EOF
$RUBY: $VER
virtualized on $(date) as
$DIR/bin/ruby
EOF

chmod 0755 bin/*

cat VIRTUALRB
